title: Sonia Beslika # your name (or website title) here
logo: "/images/circle-profile.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Maths Undergraduate at The Open University
  <br><br>
  Chair of the <a href=" https://linktr.ee/ouweatherandclimateclub">OU Weather & Climate Club</a>
  <br><br>
  <a href="www.linkedin.com/in/sonia-beslika-845b41289">My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.datacamp.com/portfolio/soniabeslika">My DataCamp Portfolio</a> 
  <br><br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
